#Server info...
---
liquibase:
  change-log: classpath:db/changelog/db.example-changelog.xml
---
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    ca.purpleowl.examples.spring.boot: INFO
---
management:
  port: 8081
---
server:
  port: 8085
---
spring:
  profiles:
    active: integration, sql-debug
---

#This profile is used for integration tests, when we're only running this Spring Boot application.  We still need a
#database to point to for any integration tests that require one to be present.  This serves that purpose perfectly.
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password:
    url: jdbc:h2:mem:test;mode=MySQL
    username: SA
  jpa:
    hibernate:
      #We don't want this functionality.  We're using Liquibase instead of magic.
      ddl-auto: none
    database: h2
  profiles: integration
---
#This profile provides full debug of generated SQL and can be very useful for customizing queries.
spring:
  profiles: sql-debug
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE